language: rust
cache: cargo
before_script:
- export PATH="$PATH:$HOME/.cargo/bin"
- rustup component add rustfmt
script:
- cargo fmt -- --check
- cargo build
- cargo test
- cargo build --all-features
- cargo test --all-features
- cargo doc --all-features
- cargo build --manifest-path capnp/Cargo.toml
- cargo test --manifest-path capnp/Cargo.toml
- cargo build --manifest-path capnp/Cargo.toml --all-features
- cargo test --manifest-path capnp/Cargo.toml --all-features
- cargo doc --manifest-path capnp/Cargo.toml --all-features
