[package]
name = "rast"
version = "0.1.0"
authors = ["Daniel Harrison <daniel.harrison@gmail.com>"]
edition = "2018"

[dependencies]
extreme = "666.666.666666"

[dependencies.rand]
version = "0.7"
features = ["small_rng"]
