[package]

name = "benchmark"
version = "0.0.0"
authors = ["Daniel Harrison <daniel.harrison@gmail.com>"]
edition = "2018"

[dependencies]
capnp_runtime = { path = "../runtime" }
os_pipe = "0.9"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "run_all"
harness = false

[workspace]
